### PR TITLE
Us01 path

### PR DESCRIPTION
**Pull request by ChaMm17**

### CODE REVIEW

**Review by Davido91390 — APPROVED** [review]
Nice

**Review by RossAlex0 — APPROVED** [review]
Good Job !! 💪

**Review by RossAlex0 — APPROVED** [review]
Perfect ! 👍

**Review by kpeset — CHANGES_REQUESTED** [review]
Table favori ,  FavoriActions et FavoriRepository ? ;)

**Review by kpeset — APPROVED** [review]

**Pull request merged**
